name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: PrintGreeting
        run: echo "Hello world"
      - name: PrintGoodbye
        run: echo "See ya later!"
        
